/linux
    protocol: efi
    path: boot():/EFI/Linux/arch-linux.efi
    cmdline: cryptdevice=PARTUUID=6fbe7c3f-1975-457e-8216-4579a1cbb987:root root=/dev/mapper/root zswap.enabled=0 rootflags=subvol=@ rw rootfstype=btrfs quiet splash loglevel=3 vt.global_cursor_default=0 vconsole.keymap=fr

/linux-lts
    protocol: efi
    path: boot():/EFI/Linux/arch-linux-lts.efi
    cmdline: cryptdevice=PARTUUID=6fbe7c3f-1975-457e-8216-4579a1cbb987:root root=/dev/mapper/root zswap.enabled=0 rootflags=subvol=@ rw rootfstype=btrfs quiet splash loglevel=3 vt.global_cursor_default=0 vconsole.keymap=fr
