[terminal]
vt = 1

[default_session]
command = "env GSK_RENDERER=cairo XCURSOR_THEME=macOS XCURSOR_SIZE=16 WLR_DRM_DEVICES=/dev/dri/intel-igpu XKB_DEFAULT_LAYOUT=fr LIBSEAT_BACKEND=logind HOME=/var/lib/greetd XDG_CONFIG_HOME=/etc/greetd/xdg cage -d -s -- regreet --style /etc/greetd/regreet.css >/dev/null 2>&1"
user = "greeter"
