# Auto-generated by matugen — do not edit by hand.
# Sourced by ~/.config/zsh/rc.d/40-plugin-settings.zsh.
# Regenerates on every wallpaper change via hypr-themectl.

# Material-You roles (hex, no leading '#' needed for zsh styles)
export ZSH_COLOR_PRIMARY='#ddc66e'
export ZSH_COLOR_ON_PRIMARY='#3a3000'
export ZSH_COLOR_PRIMARY_CONTAINER='#544600'
export ZSH_COLOR_ON_PRIMARY_CONTAINER='#fae287'
export ZSH_COLOR_SURFACE='#16130b'
export ZSH_COLOR_ON_SURFACE='#e9e2d4'
export ZSH_COLOR_ON_SURFACE_VARIANT='#cdc6b4'
export ZSH_COLOR_ERROR='#ffb4ab'
export ZSH_COLOR_ON_ERROR='#690005'
export ZSH_COLOR_ERROR_CONTAINER='#93000a'
export ZSH_COLOR_ON_ERROR_CONTAINER='#ffdad6'
export ZSH_COLOR_OUTLINE_VARIANT='#4b4739'
