# Auto-generated by matugen — do not edit by hand.
# Sourced by ~/.config/zsh/rc.d/40-plugin-settings.zsh.
# Regenerates on every wallpaper change via hypr-themectl.

# Material-You roles (hex, no leading '#' needed for zsh styles)
export ZSH_COLOR_PRIMARY='#ffb2b9'
export ZSH_COLOR_ON_PRIMARY='#561d26'
export ZSH_COLOR_PRIMARY_CONTAINER='#72333b'
export ZSH_COLOR_ON_PRIMARY_CONTAINER='#ffdadc'
export ZSH_COLOR_SURFACE='#1a1112'
export ZSH_COLOR_ON_SURFACE='#f0dedf'
export ZSH_COLOR_ON_SURFACE_VARIANT='#d7c1c2'
export ZSH_COLOR_ERROR='#ffb4ab'
export ZSH_COLOR_ON_ERROR='#690005'
export ZSH_COLOR_ERROR_CONTAINER='#93000a'
export ZSH_COLOR_ON_ERROR_CONTAINER='#ffdad6'
export ZSH_COLOR_OUTLINE_VARIANT='#524344'
