# Navigation
setopt AUTO_CD AUTO_PUSHD PUSHD_IGNORE_DUPS PUSHD_SILENT PUSHD_TO_HOME

# Globbing
setopt EXTENDED_GLOB NO_NOMATCH NULL_GLOB GLOB_DOTS

# History
setopt APPEND_HISTORY INC_APPEND_HISTORY SHARE_HISTORY EXTENDED_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST HIST_IGNORE_DUPS HIST_IGNORE_ALL_DUPS
setopt HIST_FIND_NO_DUPS HIST_IGNORE_SPACE HIST_REDUCE_BLANKS
setopt HIST_VERIFY HIST_SAVE_NO_DUPS

# Completion
setopt COMPLETE_IN_WORD ALWAYS_TO_END AUTO_MENU AUTO_LIST
setopt AUTO_PARAM_SLASH NO_MENU_COMPLETE NO_LIST_BEEP LIST_PACKED LIST_TYPES

# I/O
setopt NO_BEEP NO_FLOW_CONTROL INTERACTIVE_COMMENTS NO_CLOBBER
setopt CORRECT NO_CORRECT_ALL

# Jobs & Prompt
setopt LONG_LIST_JOBS AUTO_RESUME NOTIFY
setopt PROMPT_SUBST TRANSIENT_RPROMPT
