# Shell variables
# Generated by 'wal'
wallpaper='/home/uncle_j4ck/Pictures/wallpapers/Wallpaper-Snake-Ouroboros-Chun-Lo-Bones-Serpent-Digit19.jpg'

# Special
background='#0d0c0d'
foreground='#e4d8d5'
cursor='#e4d8d5'

# Colors
color0='#0d0c0d'
color1='#C2313B'
color2='#AC5259'
color3='#AA7E80'
color4='#B28C8E'
color5='#C89B9C'
color6='#CDAEAF'
color7='#e4d8d5'
color8='#9f9795'
color9='#C2313B'
color10='#AC5259'
color11='#AA7E80'
color12='#B28C8E'
color13='#C89B9C'
color14='#CDAEAF'
color15='#e4d8d5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
