--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/uncle_j4ck/Pictures/wallpapers/Wallpaper-Snake-Ouroboros-Chun-Lo-Bones-Serpent-Digit19.jpg"

-- Special
background="#0d0c0d"
foreground="#e4d8d5"
cursor="#e4d8d5"

-- Colors
color0="#0d0c0d"
color1="#C2313B"
color2="#AC5259"
color3="#AA7E80"
color4="#B28C8E"
color5="#C89B9C"
color6="#CDAEAF"
color7="#e4d8d5"
color8="#9f9795"
color9="#C2313B"
color10="#AC5259"
color11="#AA7E80"
color12="#B28C8E"
color13="#C89B9C"
color14="#CDAEAF"
color15="#e4d8d5"
