--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/uncle_j4ck/Pictures/Wallpapers/968265.png"

-- Special
background="#100f0f"
foreground="#dd9c8a"
cursor="#dd9c8a"

-- Colors
color0="#100f0f"
color1="#5C4831"
color2="#9A241D"
color3="#8F3227"
color4="#AF3628"
color5="#CA2F21"
color6="#A5452D"
color7="#dd9c8a"
color8="#9a6d60"
color9="#5C4831"
color10="#9A241D"
color11="#8F3227"
color12="#AF3628"
color13="#CA2F21"
color14="#A5452D"
color15="#dd9c8a"
