# Shell variables
# Generated by 'wal'
wallpaper='/home/uncle_j4ck/Pictures/Wallpapers/968265.png'

# Special
background='#100f0f'
foreground='#dd9c8a'
cursor='#dd9c8a'

# Colors
color0='#100f0f'
color1='#5C4831'
color2='#9A241D'
color3='#8F3227'
color4='#AF3628'
color5='#CA2F21'
color6='#A5452D'
color7='#dd9c8a'
color8='#9a6d60'
color9='#5C4831'
color10='#9A241D'
color11='#8F3227'
color12='#AF3628'
color13='#CA2F21'
color14='#A5452D'
color15='#dd9c8a'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
