# Minimal, stable Hyprland Phase-1 config

$terminal = uwsm app -- kitty
$menu = uwsm app -- rofi -show drun
$browser = uwsm app -- firefox


# Make DBus/systemd user session aware of Wayland session env
exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=Hyprland

# Create XDG user dirs on first login
exec-once = xdg-user-dirs-update

# Bar & Notifications
exec-once = uwsm app -- waybar
exec-once = uwsm app -- swaync


# Idle/lock baseline (you installed hypridle/hyprlock)
exec-once = hypridle

# Optional: notifications daemon (Phase 1 safe; no theming)
# exec-once = swaync

# Monitors
exec-once = ~/.config/hypr/scripts/monitors.sh

# Basic binds
bind = SUPER, RETURN, exec, $terminal
bind = SUPER, D, exec, $menu
bind = SUPER, F, exec, $browser
bind = SUPER, Q, killactive
bind = SUPER, M, exit, uwsm stop

# Screenshot (basic)
bind = SUPER, S, exec, grim -g "$(slurp)" - | satty --filename -

input {
  kb_layout = fr
}

misc {
  disable_hyprland_logo = true
  allow_session_lock_restore = true
}
