# Minimal, stable Hyprland Phase-1 config

$terminal = uwsm app -- kitty
$menu = uwsm app -- rofi -show drun
$browser = uwsm app -- firefox


# Make DBus/systemd user session aware of Wayland session env
exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=Hyprland

# Create XDG user dirs on first login
exec-once = xdg-user-dirs-update

# Bar & Notifications
exec-once = uwsm app -- waybar
exec-once = uwsm app -- swaync
exec-once = uwsm app -- wl-paste --type text --watch cliphist store
exec-once = uwsm app -- wl-paste --type image --watch cliphist store


# Idle/lock baseline (you installed hypridle/hyprlock)
exec-once = uwsm app -- hypridle

# Lock
bind = SUPER, L, exec, pidof hyprlock || uwsm app -- hyprlock


# Monitors
exec-once = ~/.config/hypr/scripts/monitors.sh

# Theme (reapply last)
exec-once = ~/.config/hypr/scripts/hypr-themectl/hypr-themectl.sh wallpaper --reapply

# Basic binds
bind = SUPER, RETURN, exec, $terminal
bind = SUPER, D, exec, $menu
bind = SUPER, F, exec, $browser
bind = SUPER, Q, killactive
bind = SUPER, M, exec, uwsm stop

# Screenshot (basic)
bind = SUPER, S, exec, grim -g "$(slurp)" - | satty --filename -

# Random Wallpaper + Theme reapply
bind = SUPER, W, exec, ~/.config/hypr/scripts/hypr-themectl/hypr-themectl.sh apply --random

input {
    kb_layout = fr,us
    kb_options = grp:alt_shift_toggle
}

misc {
  disable_hyprland_logo = true
  allow_session_lock_restore = true
}
