#  ┓┏┓┏┏┓┳┓┳┳┓┓ ┏┓
#  ┣┫┗┫┃┃┣┫┃┃┃┃ ┣ 
#  ┛┗┗┛┣┛┛┗┻┻┛┗┛┗┛
#                 

# ~/.config/hypr/hypridle.conf
# Hypridle Configuration File

general {
    # Start hyprlock only once (prevents duplicates)
    lock_cmd = pidof hyprlock || hyprlock

    # Always lock before suspend
    before_sleep_cmd = loginctl lock-session

    after_sleep_cmd = hyprctl dispatch dpms on

    # Respect inhibitors (video calls, presentations, etc.)
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
    ignore_wayland_inhibit = false
}

listener {
    timeout = 3000
    on-timeout = brightnessctl -sd intel_backlight set 10%
    on-resume = brightnessctl -rd intel_backlight
}

listener {
    timeout = 3000
    on-timeout = brightnessctl -sd dell::kbd_backlight set 0
    on-resume = brightnessctl -rd dell::kbd_backlight
}

listener {
    timeout = 6000
    on-timeout = loginctl lock-session
}

listener {
    timeout = 6600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && brightnessctl -rd intel_backlight
}

listener {
    timeout = 18000
    on-timeout = systemctl suspend-then-hibernate
}

