[Service]
# Must be set before QML loads Qt Quick Controls:
Environment=QT_QUICK_CONTROLS_STYLE=org.hyprland.style
Environment=QT_QUICK_CONTROLS_CONF=%h/.config/hyprpolkit/.qtquickcontrols2.conf

# Don't force a Qt Widgets style engine (Kvantum) onto this QML app:
UnsetEnvironment=QT_STYLE_OVERRIDE

