-- Auto-generated by Matugen. DO NOT EDIT.
-- This template is rendered to: ~/.config/nvim/colors/matugen.lua

local ok, base16 = pcall(require, "mini.base16")
if not ok then
  return
end

local palette = {
  base00 = "{{ colors.background.default.hex }}",
  base01 = "{{ colors.surface_container_lowest.default.hex }}",
  base02 = "{{ colors.surface_container.default.hex }}",
  base03 = "{{ colors.outline_variant.default.hex }}",
  base04 = "{{ colors.on_surface_variant.default.hex }}",
  base05 = "{{ colors.on_surface.default.hex }}",
  base06 = "{{ colors.surface_bright.default.hex }}",
  base07 = "{{ colors.surface_container_highest.default.hex }}",

  base08 = "{{ colors.error.default.hex }}",
  base09 = "{{ colors.tertiary.default.hex }}",
  base0A = "{{ colors.warning.default.hex }}",
  base0B = "{{ colors.success.default.hex }}",
  base0C = "{{ colors.info.default.hex }}",
  base0D = "{{ colors.primary.default.hex }}",
  base0E = "{{ colors.secondary.default.hex }}",
  base0F = "{{ colors.primary_container.default.hex }}",
}

local function is_light(hex)
  local r = tonumber(hex:sub(2, 3), 16) or 0
  local g = tonumber(hex:sub(4, 5), 16) or 0
  local b = tonumber(hex:sub(6, 7), 16) or 0
  local luma = (0.2126 * r + 0.7152 * g + 0.0722 * b) / 255
  return luma > 0.5
end

vim.o.termguicolors = true
vim.o.background = is_light(palette.base00) and "light" or "dark"

base16.setup({
  palette = palette,
  use_cterm = true,
  plugins = { default = true },
})

vim.g.colors_name = "matugen"
