# Auto-generated by matugen — do not edit by hand.
# Sourced by ~/.config/zsh/rc.d/40-plugin-settings.zsh.
# Regenerates on every wallpaper change via hypr-themectl.

# Material-You roles (hex, no leading '#' needed for zsh styles)
export ZSH_COLOR_PRIMARY='{{ colors.primary.default.hex }}'
export ZSH_COLOR_ON_PRIMARY='{{ colors.on_primary.default.hex }}'
export ZSH_COLOR_PRIMARY_CONTAINER='{{ colors.primary_container.default.hex }}'
export ZSH_COLOR_ON_PRIMARY_CONTAINER='{{ colors.on_primary_container.default.hex }}'
export ZSH_COLOR_SURFACE='{{ colors.surface.default.hex }}'
export ZSH_COLOR_ON_SURFACE='{{ colors.on_surface.default.hex }}'
export ZSH_COLOR_ON_SURFACE_VARIANT='{{ colors.on_surface_variant.default.hex }}'
export ZSH_COLOR_ERROR='{{ colors.error.default.hex }}'
export ZSH_COLOR_ON_ERROR='{{ colors.on_error.default.hex }}'
export ZSH_COLOR_ERROR_CONTAINER='{{ colors.error_container.default.hex }}'
export ZSH_COLOR_ON_ERROR_CONTAINER='{{ colors.on_error_container.default.hex }}'
export ZSH_COLOR_OUTLINE_VARIANT='{{ colors.outline_variant.default.hex }}'
