-- Auto-generated by Matugen. DO NOT EDIT.
-- This template is rendered to: ~/.config/nvim/colors/matugen.lua

local ok, base16 = pcall(require, "mini.base16")
if not ok then
  return
end

local palette = {
  base00 = "#12140d",
  base01 = "#0d0f09",
  base02 = "#1e2019",
  base03 = "#45483c",
  base04 = "#c6c8b9",
  base05 = "#e3e3d8",
  base06 = "#383a32",
  base07 = "#34362e",

  base08 = "#ffb4ab",
  base09 = "#a0d0c8",
  base0A = "#d5c871",
  base0B = "#abd28f",
  base0C = "#99ccfa",
  base0D = "#b7d085",
  base0E = "#c2caab",
  base0F = "#3a4d11",
}

local function is_light(hex)
  local r = tonumber(hex:sub(2, 3), 16) or 0
  local g = tonumber(hex:sub(4, 5), 16) or 0
  local b = tonumber(hex:sub(6, 7), 16) or 0
  local luma = (0.2126 * r + 0.7152 * g + 0.0722 * b) / 255
  return luma > 0.5
end

vim.o.termguicolors = true
vim.o.background = is_light(palette.base00) and "light" or "dark"

base16.setup({
  palette = palette,
  use_cterm = true,
  plugins = { default = true },
})

vim.g.colors_name = "matugen"
