-- Auto-generated by Matugen. DO NOT EDIT.
-- This template is rendered to: ~/.config/nvim/colors/matugen.lua

local ok, base16 = pcall(require, "mini.base16")
if not ok then
  return
end

local palette = {
  base00 = "#101417",
  base01 = "#0a0f12",
  base02 = "#1c2024",
  base03 = "#41484d",
  base04 = "#c1c7ce",
  base05 = "#dfe3e7",
  base06 = "#353a3d",
  base07 = "#313539",

  base08 = "#ffb4ab",
  base09 = "#ccc0e9",
  base0A = "#d5c871",
  base0B = "#91d5ad",
  base0C = "#9dcbfb",
  base0D = "#92cef6",
  base0E = "#b6c9d8",
  base0F = "#004c6c",
}

local function is_light(hex)
  local r = tonumber(hex:sub(2, 3), 16) or 0
  local g = tonumber(hex:sub(4, 5), 16) or 0
  local b = tonumber(hex:sub(6, 7), 16) or 0
  local luma = (0.2126 * r + 0.7152 * g + 0.0722 * b) / 255
  return luma > 0.5
end

vim.o.termguicolors = true
vim.o.background = is_light(palette.base00) and "light" or "dark"

base16.setup({
  palette = palette,
  use_cterm = true,
  plugins = { default = true },
})

vim.g.colors_name = "matugen"
