-- Auto-generated by Matugen. DO NOT EDIT.
-- This template is rendered to: ~/.config/nvim/colors/matugen.lua

local ok, base16 = pcall(require, "mini.base16")
if not ok then
  return
end

local palette = {
  base00 = "#1a1110",
  base01 = "#140c0b",
  base02 = "#271d1c",
  base03 = "#534341",
  base04 = "#d8c2bf",
  base05 = "#f1dedc",
  base06 = "#423735",
  base07 = "#3d3231",

  base08 = "#ffb4ab",
  base09 = "#dfc38c",
  base0A = "#f5bd6f",
  base0B = "#b1d18a",
  base0C = "#b8c4ff",
  base0D = "#ffb4aa",
  base0E = "#e7bdb7",
  base0F = "#73342d",
}

local function is_light(hex)
  local r = tonumber(hex:sub(2, 3), 16) or 0
  local g = tonumber(hex:sub(4, 5), 16) or 0
  local b = tonumber(hex:sub(6, 7), 16) or 0
  local luma = (0.2126 * r + 0.7152 * g + 0.0722 * b) / 255
  return luma > 0.5
end

vim.o.termguicolors = true
vim.o.background = is_light(palette.base00) and "light" or "dark"

base16.setup({
  palette = palette,
  use_cterm = true,
  plugins = { default = true },
})

vim.g.colors_name = "matugen"
