# Misc behavior

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    vrr = 0
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
    allow_session_lock_restore = true
    focus_on_activate = false
    close_special_on_empty = true
    background_color = $background
}

debug {
    disable_logs = false
    vfr = true
}

binds {
    workspace_back_and_forth = true
    allow_workspace_cycles = true
    pass_mouse_when_bound = false
}

xwayland {
    force_zero_scaling = true
}

cursor {
    no_hardware_cursors = 2
    inactive_timeout = 5
    enable_hyprcursor = true
}

ecosystem {
    no_update_news = true
    no_donation_nag = true
}

plugin {
    split-monitor-workspaces {
        count = 9
        keep_focused = 0
        enable_notifications = 0
        enable_persistent_workspaces = 1
        link_monitors = 1
    }
}
