#  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓  ┓┏┓┳┏┳┓┏┳┓┓┏
#  ┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃━━┃┫ ┃ ┃  ┃ ┗┫
#  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗  ┛┗┛┻ ┻  ┻ ┗┛

# Core Colors
background              #16130b
foreground              #e9e2d4

cursor                  #ddc66e
cursor_text_color       #3a3000

selection_background    #d2c6a1
selection_foreground    #373016

scrollbar_handle_color  #ddc66e
url_color               #ddc66e

active_tab_background   #ddc66e
active_tab_foreground   #3a3000
inactive_tab_background #4b4739
inactive_tab_foreground #cdc6b4
tab_bar_background      #16130b

# Regular Colors
color0   #16130b
color1   #ffb4ab
color2   #ddc66e
color3   #aad0b2
color4   #d2c6a1
color5   #544600
color6   #979080
color7   #e9e2d4


# Bright Colors
color8   #4b4739
color9   #ffb4ab
color10  #ddc66e
color11  #aad0b2
color12  #d2c6a1
color13  #544600
color14  #979080
color15  #e9e2d4
