#  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓  ┓┏┓┳┏┳┓┏┳┓┓┏
#  ┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃━━┃┫ ┃ ┃  ┃ ┗┫
#  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗  ┛┗┛┻ ┻  ┻ ┗┛

# Core Colors
background              #101417
foreground              #dfe3e7

cursor                  #92cef6
cursor_text_color       #00344c

selection_background    #b6c9d8
selection_foreground    #21323e

scrollbar_handle_color  #92cef6
url_color               #92cef6

active_tab_background   #92cef6
active_tab_foreground   #00344c
inactive_tab_background #41484d
inactive_tab_foreground #c1c7ce
tab_bar_background      #101417

# Regular Colors
color0   #101417
color1   #ffb4ab
color2   #92cef6
color3   #ccc0e9
color4   #b6c9d8
color5   #004c6c
color6   #8b9198
color7   #dfe3e7


# Bright Colors
color8   #41484d
color9   #ffb4ab
color10  #92cef6
color11  #ccc0e9
color12  #b6c9d8
color13  #004c6c
color14  #8b9198
color15  #dfe3e7
