#  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓  ┓┏┓┳┏┳┓┏┳┓┓┏
#  ┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃━━┃┫ ┃ ┃  ┃ ┗┫
#  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗  ┛┗┛┻ ┻  ┻ ┗┛

# Core Colors
background              #1a1112
foreground              #f0dedf

cursor                  #ffb2b9
cursor_text_color       #561d26

selection_background    #e5bdbf
selection_foreground    #44292c

scrollbar_handle_color  #ffb2b9
url_color               #ffb2b9

active_tab_background   #ffb2b9
active_tab_foreground   #561d26
inactive_tab_background #524344
inactive_tab_foreground #d7c1c2
tab_bar_background      #1a1112

# Regular Colors
color0   #1a1112
color1   #ffb4ab
color2   #ffb2b9
color3   #e8c08e
color4   #e5bdbf
color5   #72333b
color6   #9f8c8d
color7   #f0dedf


# Bright Colors
color8   #524344
color9   #ffb4ab
color10  #ffb2b9
color11  #e8c08e
color12  #e5bdbf
color13  #72333b
color14  #9f8c8d
color15  #f0dedf
